## 二維陣列

In [2]:
import numpy as np

np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.random.randint(50,100,size=(50,5)) #50列 5欄

array([[96, 97, 53, 63, 92],
       [92, 96, 68, 90, 51],
       [87, 86, 53, 98, 79],
       [65, 76, 86, 90, 54],
       [59, 98, 71, 56, 79],
       [72, 92, 56, 90, 82],
       [77, 99, 94, 90, 61],
       [85, 53, 64, 89, 59],
       [92, 54, 82, 93, 63],
       [52, 97, 56, 76, 52],
       [75, 59, 95, 94, 65],
       [91, 89, 75, 50, 58],
       [76, 58, 89, 97, 72],
       [75, 58, 55, 85, 63],
       [58, 59, 92, 65, 87],
       [84, 69, 60, 90, 86],
       [85, 61, 65, 67, 81],
       [80, 76, 88, 75, 62],
       [82, 67, 67, 73, 91],
       [74, 55, 95, 58, 73],
       [85, 79, 69, 76, 99],
       [70, 89, 83, 53, 86],
       [75, 83, 68, 99, 74],
       [94, 80, 72, 82, 92],
       [68, 57, 74, 65, 61],
       [64, 62, 92, 60, 69],
       [81, 98, 51, 86, 85],
       [70, 69, 94, 67, 81],
       [96, 69, 98, 84, 89],
       [65, 60, 55, 57, 78],
       [64, 92, 63, 96, 65],
       [71, 67, 54, 55, 64],
       [93, 72, 51, 95, 60],
       [54, 61, 57, 70, 79],
       [99, 86

## 三維陣列

In [ ]:
np.random.randint(50,100,size=(3,50,5)) #3個班 50列 5欄

array([[[70, 70, 58, 66, 96],
        [56, 99, 63, 71, 66],
        [82, 89, 51, 61, 50],
        [91, 78, 62, 61, 75],
        [51, 70, 58, 60, 90],
        [70, 67, 86, 96, 64],
        [64, 76, 80, 59, 75],
        [65, 71, 82, 72, 91],
        [71, 74, 77, 82, 94],
        [78, 88, 88, 56, 54],
        [84, 50, 86, 77, 89],
        [61, 88, 65, 77, 84],
        [94, 62, 61, 78, 67],
        [53, 90, 91, 56, 50],
        [79, 88, 99, 82, 71],
        [83, 69, 61, 50, 74],
        [59, 50, 84, 73, 92],
        [75, 79, 97, 74, 71],
        [63, 91, 57, 74, 81],
        [69, 58, 62, 88, 63],
        [94, 65, 95, 58, 59],
        [62, 89, 51, 63, 89],
        [59, 96, 72, 83, 79],
        [82, 97, 88, 95, 64],
        [83, 96, 68, 56, 86],
        [56, 89, 74, 89, 88],
        [81, 73, 87, 88, 93],
        [83, 64, 52, 84, 96],
        [85, 86, 77, 66, 57],
        [56, 98, 53, 50, 54],
        [57, 89, 76, 85, 90],
        [50, 81, 91, 68, 81],
        [76, 96, 88, 55, 94],
        [5

In [ ]:
#查詢的property -> shape(形狀), size(多少個), dtype(型別), ndim(維度)

grade5 = np.random.randint(50,100,size=(3,50,5)) #3個班 50列 5欄
grade5.shape, grade5.size, grade5.ndim, grade5.dtype

((3, 50, 5), 750, 3, dtype('int64'))