In [3]:
#list 資料

a = [1,2,3,4,5]
b = [9,8,7,6,5]
c = a + b #增加元素數量
print(c)

for value in c:
    print(value,end='')

[1, 2, 3, 4, 5, 9, 8, 7, 6, 5]
1234598765

# 外部的資料結構
### 1. numpy 陣列運算 
- ndarray
### 2. pandas 陣列運算 
- Series 
- DataFrame

In [5]:
import numpy as np 
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [6]:
array2 = np.array([9,8,7,6,5])
array2

array([9, 8, 7, 6, 5])

In [ ]:
#可以直接進行陣列相加
array3 = array1 + array2
array3
array4 = array3 * 10
array4


array([100, 100, 100, 100, 100])

In [16]:
np.empty((2,))

array([-2.00000000e+000,  6.83698499e-310])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])